change language in dropdown on language click
DavidDyberg/Wikipedia pull request #17
Opened 2023-08-24 09:28 UTC by maxhaggmancmedu

2023-08-24 11:13 UTC, DavidDyberg commented on src/App.js
> +
Remove this row

2023-08-24 11:15 UTC, DavidDyberg commented on src/components/select/index.css
> +
Remove row 15,16 and 17

2023-08-24 11:17 UTC, DavidDyberg requested changes
Remove empty rows at "src/components/select/index.css"

2023-08-24 11:22 UTC, maxhaggmancmedu commented
Empty rows have been removed now, please review again!

2023-08-24 11:24 UTC, DavidDyberg approved these changes

2023-08-24 14:23 UTC, CyberGalactus approved these changes

2023-08-24 14:40 UTC, CyberGalactus approved these changes

2023-08-24 14:41 UTC, DavidDyberg approved these changes

2023-08-24 14:42 UTC, DavidDyberg approved these changes

2023-08-25 08:07 UTC, DavidDyberg approved these changes

2023-08-25 08:44 UTC, merged